= Forking

Before you start to develop your project you have to tweak the python-template
to suit your needs. This is minimal checklist you want to follow to update the
code to your needs.


== 0. Git project preparation

The first step is to prepare empty git project. You want to create the empty
directory, place bare-bone readme and add that to the new git repository. The
following code should give you the idea of what you should do:

[,sh]
----
mkdir newproj
cd newproj
cat >README.adoc <<EOF
= New project
CZ.NIC z.s.p.o. <software@turris.cz>
v0.0, 2022-01-01
:icons:

This project is the new project. Make sure to describe here your project before
commiting as well as changing the name of the project on the first line.
EOF
git init
git commit --gpg-sign --message 'Initial commit' README.adoc
git checkout --branch dev
----

You can of course skip the project initialization step if you are updating an
existing project.

The next step is to merge the python-template to your new project.

[,sh]
----
git remote add template https://gitlab.nic.cz/turris/python-template.git
git fetch template
git merge --allow-unrelated-historie template/master
----

You have to resolve merge conflict in the `README.adoc` file to complete the
merge.

The following steps are going to be about modifying the files introduced by
merge and as last step we squash all changes to the merge commit so our history
starts nice and clean.


== 1. Rename the project

The first step is for sure the project rename. The python-template uses
`python-template` name in various locations and this should be name of your
project instead. You can use `grep -Rn python-template` to locate all
occurrences of `python-template`. To rename all relevant code should be:

[,sh]
----
set -i 's/python-template/newproj/g' README.adoc setup.py
----

Note that the suggestion here might not be all so you should verify all usages
of `python-template` string in the project on your own as it is easier for us to
cover places where `python-template` should stay rather than opposite.

The `python-template` should be kept in the following files:

- `.gitlab-ci.yml` as there it references common base stored in python-template
  repository. The referenced branch won't and should not be available in your
  project.
- `.gitlab-ci/Dockerfile-*` files reference image build and maintained centrally
  in the python-template registry thus reference should not be changed there.



== 2. Replicate and rename package

It is higly preffered to always use Python module over just plain Python script.
The module should be named with project name, unless there is important reason
why that should not be the case. The allowed replacement is `-` with `_`.

Make sure that you also update the name of the module, descriptions and
everything related to that in the `setup.py` file.

It is also allowed that there is no `setup.py` in case there is no reason to
ever install module. In such case you should remove `setup.py` file, but you
should always replace it with `requirements.txt` file that contains all
dependencies.

Feel free to also remove `Makefile` and `foo/locale` if you are not planning on
using localization. In case you do make sure that the POT file in locale
directory is named correctly. You also have to change the name of the module at
the end of the `Makefile`. You can also add new modules there inn case you have
multiple modules.


== 3. Cleanup

Remove any python-template specific files. These are files such as this
documentation.

[,sh]
----
rm -rf docs
----

Do not forget to write your own documentation!


== 5. Commit all changes as part of merge commit

The last step is to stage all changes you made and modify merge commit created at
the beginning. This can be done by:

[sh]
----
git commit --amend -C HEAD .
----
